"""Emitters: turn corpus cases into shareable fixture files.

The corpus is only useful if it escapes Python: the JSON/JSONL/CSV emitters
exist so a Go, Java, or TypeScript team can consume the exact same cases from
one committed file. Output is fully deterministic (sorted keys, stable case
order, trailing newline) so emitted fixtures diff cleanly in git.
"""

from __future__ import annotations

import csv
import io
import json
from typing import Callable, Dict, Sequence

from .model import Case

#: Registered emitter names, in the order the CLI advertises them.
FORMATS: Dict[str, str] = {
    "json": "single JSON document with metadata and a `cases` array",
    "jsonl": "one compact JSON object per line, no wrapper",
    "csv": "flat table; `utc` and `tags` are |-joined",
    "markdown": "GitHub-flavored table for docs and PR descriptions",
    "pytest": "self-contained pytest parametrization module",
}


def _dicts(items: Sequence[Case]):
    return [item.as_dict() for item in items]


def emit_json(items: Sequence[Case], version: str) -> str:
    """One JSON document: metadata header plus every case, sorted keys."""
    document = {
        "generator": "edgetz",
        "version": version,
        "count": len(items),
        "cases": _dicts(items),
    }
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def emit_jsonl(items: Sequence[Case], version: str) -> str:
    """One compact JSON object per line — the format for streaming/polyglot use."""
    del version  # jsonl carries no wrapper by design
    lines = [
        json.dumps(entry, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
        for entry in _dicts(items)
    ]
    return "\n".join(lines) + "\n"


def emit_csv(items: Sequence[Case], version: str) -> str:
    """Flat CSV; multi-valued fields are |-joined, `expect` is inline JSON."""
    del version
    columns = [
        "id", "category", "kind", "zone", "local", "literal",
        "utc", "tags", "verify", "why", "source", "expect",
    ]
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(columns)
    for entry in _dicts(items):
        writer.writerow(
            [
                entry["id"],
                entry["category"],
                entry["kind"],
                entry["zone"] or "",
                entry["local"] or "",
                entry["literal"] or "",
                "|".join(entry["utc"]),
                "|".join(entry["tags"]),
                entry["verify"],
                entry["why"],
                entry["source"],
                json.dumps(entry["expect"], sort_keys=True, separators=(",", ":")),
            ]
        )
    return buffer.getvalue()


def emit_markdown(items: Sequence[Case], version: str) -> str:
    """A GitHub-flavored table: one row per case, pipes escaped."""
    del version

    def cell(text: str) -> str:
        return text.replace("|", "\\|").replace("\n", " ")

    lines = [
        "| id | category | zone | when | utc | why |",
        "|---|---|---|---|---|---|",
    ]
    for item in items:
        lines.append(
            "| `{id}` | {category} | {zone} | `{when}` | {utc} | {why} |".format(
                id=item.id,
                category=item.category,
                zone=item.zone or "-",
                when=item.when,
                utc=", ".join(f"`{value}`" for value in item.utc) or "-",
                why=cell(item.why),
            )
        )
    return "\n".join(lines) + "\n"


def emit_pytest(items: Sequence[Case], version: str) -> str:
    """A self-contained pytest module: data inlined, no edgetz import needed.

    Teams can vendor the generated file into a repository that must not grow
    a dependency; re-generate with the same command to update it.
    """
    import pprint

    # pprint (not json.dumps) because the payload must be *Python* source:
    # JSON's null/true/false are not valid Python literals.
    payload = pprint.pformat(_dicts(items), width=88, sort_dicts=True)
    return (
        '"""Pathological datetime fixtures.\n'
        "\n"
        f"Generated by `edgetz emit --format pytest` (edgetz {version}).\n"
        "Self-contained on purpose: vendor this file, or re-generate it to update.\n"
        '"""\n'
        "\n"
        "import pytest\n"
        "\n"
        f"CASES = {payload}\n"
        "\n"
        'IDS = [case["id"] for case in CASES]\n'
        "\n"
        "\n"
        "@pytest.fixture(params=CASES, ids=IDS)\n"
        "def edge_case(request):\n"
        '    """One pathological datetime case per parametrized test run."""\n'
        "    return request.param\n"
    )


EMITTERS: Dict[str, Callable[[Sequence[Case], str], str]] = {
    "json": emit_json,
    "jsonl": emit_jsonl,
    "csv": emit_csv,
    "markdown": emit_markdown,
    "pytest": emit_pytest,
}


def emit(items: Sequence[Case], fmt: str, version: str) -> str:
    """Render cases in the named format; raises ``KeyError`` on unknown fmt."""
    return EMITTERS[fmt](items, version)
